// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF5UuYDvDR4xVxGlTysHdQPEuIbOhWVrk',
    appId: '1:212888684168:web:6d44c34b14a5056171413d',
    messagingSenderId: '212888684168',
    projectId: 'chat-system-889bd',
    authDomain: 'chat-system-889bd.firebaseapp.com',
    storageBucket: 'chat-system-889bd.firebasestorage.app',
    measurementId: 'G-D3R1YGHL8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRymCNX_9qHUiNpA09YX95m-Jqn4jiUg',
    appId: '1:212888684168:android:f6981726db7d09b771413d',
    messagingSenderId: '212888684168',
    projectId: 'chat-system-889bd',
    storageBucket: 'chat-system-889bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qQg8WyJ56-I08bp5QXSiAagvnqndmR8',
    appId: '1:212888684168:ios:87f514b116014b6871413d',
    messagingSenderId: '212888684168',
    projectId: 'chat-system-889bd',
    storageBucket: 'chat-system-889bd.firebasestorage.app',
    iosClientId: '212888684168-nbteuui7lv7l13d9g63u2ueid4omfjg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qQg8WyJ56-I08bp5QXSiAagvnqndmR8',
    appId: '1:212888684168:ios:87f514b116014b6871413d',
    messagingSenderId: '212888684168',
    projectId: 'chat-system-889bd',
    storageBucket: 'chat-system-889bd.firebasestorage.app',
    iosClientId: '212888684168-nbteuui7lv7l13d9g63u2ueid4omfjg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF5UuYDvDR4xVxGlTysHdQPEuIbOhWVrk',
    appId: '1:212888684168:web:814162c29b6fa36171413d',
    messagingSenderId: '212888684168',
    projectId: 'chat-system-889bd',
    authDomain: 'chat-system-889bd.firebaseapp.com',
    storageBucket: 'chat-system-889bd.firebasestorage.app',
    measurementId: 'G-NCR19T51E2',
  );
}
